# .github/workflows/ci.yml
name: FAU Framework CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint
    
    - name: Run unit tests
      run: npm test
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    
    - name: Build framework
      run: npm run build
    
    - name: Run integration tests
      run: npm run test:integration
      
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ matrix.node-version }}
        path: |
          fau-results/
          coverage/
        retention-days: 30

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

---

# .github/workflows/example-project.yml  
name: Example FAU Project

on:
  schedule:
    - cron: '0 9 * * *' # Daily at 9 AM
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    
    - name: Install FAU Framework
      run: npm install fau-framework
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    
    - name: Run FAU tests
      run: npx fau run --headless
      env:
        CI: true
    
    - name: Upload results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: fau-test-results
        path: fau-results/

---

# Dockerfile
FROM mcr.microsoft.com/playwright:v1.40.0-focal

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY . .

# Build the framework
RUN npm run build

# Create non-root user
RUN groupadd -r fau && useradd -r -g fau -G audio,video fau \
    && mkdir -p /home/fau/Downloads \
    && chown -R fau:fau /home/fau \
    && chown -R fau:fau /app

# Switch to non-root user
USER fau

# Set default command
CMD ["npm", "test"]

---

# docker-compose.yml
version: '3.8'

services:
  fau-tests:
    build: .
    volumes:
      - ./tests:/app/tests
      - ./fau-results:/app/fau-results
      - ./fau.config.ts:/app/fau.config.ts
    environment:
      - CI=true
      - HEADLESS=true
    command: npx fau run --headless

  fau-debug:
    build: .
    volumes:
      - ./tests:/app/tests
      - ./fau-results:/app/fau-results
      - ./fau.config.ts:/app/fau.config.ts
    ports:
      - "9222:9222"
    environment:
      - DEBUG=true
    command: npx fau debug tests/example.fau.ts

---

# .dockerignore
node_modules
npm-debug.log
.git
.gitignore
README.md
.env
.nyc_output
coverage
.coverage
fau